name: Trigger Main Repo

on:
  push:
    branches:
      - main  # 或你要监听的分支

jobs:
  notify-main-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger main repo's workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.MAIN_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/zacksleo/tcb-htmls/actions/workflows/import-html.yml/dispatches \
            -d '{"ref":"main"}'
